spring.application.name=linkshortener
server.port=8080

# PostgreSQL configuration
# These can be overridden by environment variables at runtime
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/linkshortener}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false